### ISSUE TITLE
cover size

### ISSUE THREAD

**Issue by yellow-relo** [RemixDev/DRemixIssues#113] opened 2019-12-06 14:29 UTC
Hello

If cover size is set to be downloaded at 1400x1400, the app download the cover in this size.

But if you set to download it at 2000x2000 and if it's not available à 2000x2000, it fall back to 1200x12000 and not fall back at at 1400x1400 (even if the 1400x1400 is possible when set at this size)

**Comment by RemixDev** [comment] 2019-12-06 15:51
Duplicate of #101 
Closing.

**Closed by RemixDev** 2019-12-06 15:51 UTC
Labels: bug
