### ISSUE TITLE
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.

### ISSUE THREAD

**Issue by Superhackman** [RemixDev/DRemixIssues#71] opened 2019-10-19 02:06 UTC
![image](https://user-images.githubusercontent.com/27593140/67136322-6d4e4c80-f1ea-11e9-8e3e-136405ee5b96.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Version 18363
- Did you build it from the repo?: yes
 - If so which branch?: 

**Log File**
[2019-10-19T01_59_39_311Z-debug.log](https://github.com/RemixDev/DRemixIssues/files/3746108/2019-10-19T01_59_39_311Z-debug.log)

Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.

**Comment by RemixDev** [comment] 2019-10-19 09:15
Duplicate of #10

Closing

**Closed by RemixDev** 2019-10-19 09:15 UTC
Labels: bug
