### ISSUE TITLE
The song Tusa does not appear in the search and not all the songs of Karol G or other artists, apart from missing many more songs and in better qualities, please solve this please.

### ISSUE THREAD

**Issue by Edushi** [RemixDev/DRemixIssues#161] opened 2020-02-09 20:29 UTC
[**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Did you build it from the repo?:
 - If so which branch?: 

**Log File**
Upload your log file to pastebin and paste the link here, can be helpfull sometimes

**Possible Implementation**
Not obligatory, but suggest an idea for implementing addition or change

**Additional context**
Add any other context about the problem here.]( #url)

**Comment by RemixDev** [comment] 2020-02-09 20:31
Duplicate of #160

**Closed by RemixDev** 2020-02-09 20:31 UTC
Labels: bug
