### ISSUE TITLE
Random flac downloads get stuck without error message 

### ISSUE THREAD

**Issue by Didacvs** [RemixDev/DRemixIssues#144] opened 2020-01-16 16:29 UTC
I would like to report that sometimes downloads of flac files get stuck when downloading complete albums without any failure. They simply get stuck until you see it's so and the decide it's time to either remove the whole album, or stop the downloads, or close the program and open it again.
The worst part is that the interrupted files are there and seem to have completed correctly, but they haven't, and indeed they're incomplete. The track length appears to be the right one, but when you play it the music stops at a certain time. I also notice that something is wrong by checking the file size (for instance if I see that a flac song of 9MB should last 6 minutes, then I know it's incomplete and that it simply didn't download OK).
If after removing the album from the download list when a file gets stuck, you add it again, then the incomplete file remains the same, so the result is that you think you have a complete file which is not.
I download files in sets of 3 (default program option), and so when a download sticks, I must check all the songs inside the folder, delete incomplete ones and download the album again. 
First it would be great if the downloads didn't fail. I tend to think it could be an overload of the servers, but I don't really know. It would also be nice to have a better solution than checking all the files one by one, at least that the downloads would fail after a long time and that the file didn't appear to be complete.
Finally maybe someone knows how to check that the files are complete, maybe there's a software or something. I've always used DeezloaderRemix 4.3.0 and this issue has happened to me since the beginning, but at that time when a download stuck, I just didn't know that the files were incomplete, so now I can't really know how many of the music files in my collection are affected :(

**Comment by RemixDev** [comment] 2020-01-16 16:36
Know issue and atm I have no idea on how to fix it

Also closing for duplicate of #131

**Closed by RemixDev** 2020-01-16 16:36 UTC
Labels: bug

**Comment by steve1977** [comment] 2020-01-17 14:55
Thanks for your note. Do you know whether this is only happening for flac or also for mp3?

I don't think it is server overload as it seems to happen consistently with some albums. For example: https://www.deezer.com/en/album/122615972 never completes for me.

Even if this cannot be "fixed", would it be possible to include a "time out feature" that would move on to the next download if the download of a specific file does not complete after 10min or so?

**Comment by RemixDev** [comment] 2020-01-17 15:11
There is already a timeout in the code, but it doesn't get respected
That's why I cant fix it
