### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir

### ISSUE THREAD

**Issue by mekibe** [RemixDev/DRemixIssues#38] opened 2019-08-22 11:52 UTC
**Describe the bug**
it does not matter what I download whether album or song or playlist I get over all this mistake

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version 4.2.3
 - Did you build it from the repo?:Yes
 - If so which branch?: development

**Log File**
https://pastebin.com/B5fU42f6

**Comment by RemixDev** [comment] 2019-10-05 17:37
Can you check if it's fixed with the latest commit?
I can't reproduce the issue on my pc

**Closed** 2019-10-07 15:42 UTC
Labels: bug
