### ISSUE TITLE
Download added to queue via REST API fail, works when added manually from UI

### ISSUE THREAD

**Issue by pedja1** [RemixDev/DRemixIssues#206] opened 2020-04-07 17:33 UTC
**Describe the bug**
When album/track is added to the download queue via API, download fails. When the same album/track is added via UI, it downloads fine. 
Only happens with certain tracks/albums
Example: https://www.deezer.com/album/136904492

**To Reproduce**
1. Make rest api call to download album:  
`curl -s --request GET "http://127.0.0.1:1730/api/download/?url=https://www.deezer.com/album/136904492&quality=flac`  
2. Go to Deezloader Remix UI, Downloads Tab
3. Download is marked as failed with error message:  
`Error: Error: Authentication needed to get download URL`  

**Expected behavior**
Download isn't failing when when added via api

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.3.0
 - Did you build it from the repo?: NO
 - If so which branch?: NO

**Log File**
Upload your log file to pastebin and paste the link here, can be helpfull sometimes

**Additional context**
Premum deezer account used, if it makes any difference

**Comment by RemixDev** [comment] 2020-04-07 17:51
Duplicate of #203

**Closed by RemixDev** 2020-04-07 17:51 UTC
Labels: bug
