### ISSUE TITLE
Explicit Tags

### ISSUE THREAD

**Issue by Gargantua01** [RemixDev/DRemixIssues#92] opened 2019-11-18 00:52 UTC
hi there i added %explicit% in the track names and it still wont tag the songs with explicit although you can see the tags on deezloader search with the red E
<img width="1440" alt="Screen Shot 2019-11-17 at 8 51 09 PM" src="https://user-images.githubusercontent.com/53588719/69017241-0a340f00-097c-11ea-875b-661bd324fa6c.png">

**Additional context**

**Comment by RemixDev** [comment] 2019-11-18 07:32
Duplicate of #40 and #65 
Closing.

**Closed by RemixDev** 2019-11-18 07:32 UTC
Labels: feature requests
