### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by Cabxxse** [RemixDev/DRemixIssues#205] opened 2020-04-06 21:19 UTC
**Describe the bug**
Wen I try to download it shows an Error that says: Error: Authentication needed to get download URL

**To Reproduce**
1. Try to download any song
2. See error

**Expected behavior**
Download a song

**Desktop (please complete the following information):**
 - OS: Android
 - Version 2.5.8 and 2.5.9 (I've tried to download a song in both

**Log File**
  ##https://pastebin.com/ErArgKH8

**Comment by RemixDev** [comment] 2020-04-06 21:21
Duplicate of #204

**Closed by RemixDev** 2020-04-06 21:21 UTC
Labels: bug

**Comment by Cabxxse** [comment] 2020-04-06 21:23
Thx, that was a quick answer
